Add github template to sharing page
jeertmans/manim-slides pull request #279
Opened 2023-10-01 18:12 UTC by taiyeoguns

## Fixes Issue

Closes #268

## Description

Add information about Github template to sharing page

## Check List (Check all the applicable boxes)

- [x] I understand that my contributions needs to pass the checks.
- [ ] If I created new functions / methods, I documented them and add type hints.
- [ ] If I modified already existing code, I updated the documentation accordingly.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-10-01 20:54 UTC, jeertmans requested changes

2023-10-01 20:54 UTC, jeertmans commented on docs/source/reference/sharing.md
> +
Can you split lines such that they never make more than 81 characters wide?

This is more a style requirements, but makes reading the code easier :-)

2023-10-01 20:54 UTC, jeertmans commented
Hello @taiyeoguns, thanks for your PR! I just left one comment :-)

2023-10-02 10:29 UTC, taiyeoguns commented
Thanks @jeertmans, made the update

2023-10-02 10:53 UTC, jeertmans commented
Thanks a lot!

2023-10-05 08:03 UTC, merged