fix(convert): Blank web page when converting multiple slides into HTML
jeertmans/manim-slides pull request #497
Opened 2024-12-03 13:57 UTC by simanglam

## Fixes Issue
When manin-slides convert multiple slides into html, it add prefix to animation file in asset directory to prevent filename collision (as https://github.com/jeertmans/manim-slides/issues/428 mentioned) but doesn't add the prefix in HTML's reference to the file.

## Description

I modified the HTML templates and pass prefix function to it.

## Check List

Check all the applicable boxes:

- [v] I understand that my contributions needs to pass the checks;
- [v] If I created new functions / methods, I documented them and add type hints;
- [v] If I modified already existing code, I updated the documentation accordingly;
- [v] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2024-12-03 17:16 UTC, jeertmans commented
Hi @simanglam, thanks for this PR! It looks all good, but could you add some words about this in the CHANGELOG?

2024-12-03 17:45 UTC, simanglam commented
Hi @jeertmans, I've add some words about this in the CHANGELOG. Hope I didn't make any typo or grammar error.

2024-12-03 22:03 UTC, jeertmans commented on CHANGELOG.md
> +- Fixed blank web page when converting multiple slides into HTML [#497](https://github.com/jeertmans/manim-slides/pull/497)
```suggestion
- Fixed blank web page when converting multiple slides into HTML.
  [#497](https://github.com/jeertmans/manim-slides/pull/497)
```

2024-12-03 22:03 UTC, jeertmans requested changes
Thanks! Small change requested :)

2024-12-04 03:46 UTC, simanglam commented
Done!

2024-12-04 11:25 UTC, jeertmans commented
Perfect, thanks @simanglam!

2024-12-04 11:25 UTC, merged